[package]
name = "airnope"
version = "0.0.1"
edition = "2021"

[dependencies]
acap = "0.3.0"
actix-cors = "0.7.0"
actix-web = "4.8.0"
anyhow = "1.0.86"
dashmap = "6.0.1"
log = "0.4.22"
lru = "0.12.4"
pretty_env_logger = "0.5.0"
regex = "1.10.5"
rust-bert = { version = "0.22.0", features = ["download-libtorch"] }
serde = "1.0.205"
teloxide = { version = "0.12.2", features = ["ctrlc_handler"] }
tokio = { version = "1.39.2", features = ["rt-multi-thread", "macros", "fs", "rt"] }
