app = 'airnope-bot'
primary_region = 'ams'
swap_size_mb = 512

[build]

[processes]
  web = "airnope bot --mode webhook --shutdown-in 120"

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 1
  processes = ['web']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[[restart]]
  policy = "always"
